# Generated by Django 5.1.3 on 2024-11-23 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0002_best_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='best_teacher',
            name='image',
            field=models.ImageField(upload_to='best_teachers_image/'),
        ),
    ]
