# Generated by Django 5.1.3 on 2024-12-03 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0002_category_blog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='imgae',
            new_name='image',
        ),
    ]
