# Generated by Django 5.1.3 on 2024-12-05 13:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0006_servise'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='work',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='work',
            name='description',
        ),
        migrations.AddField(
            model_name='blog',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='work',
            name='category',
            field=models.ManyToManyField(to='Article.category'),
        ),
        migrations.RemoveField(
            model_name='blog',
            name='category',
        ),
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(upload_to='image_blog/'),
        ),
        migrations.AlterField(
            model_name='work',
            name='image',
            field=models.ImageField(upload_to='image_work/'),
        ),
        migrations.DeleteModel(
            name='Servise',
        ),
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.ManyToManyField(to='Article.category'),
        ),
    ]
