# Generated by Django 5.1.3 on 2024-12-05 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0008_work_create_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
