# Generated by Django 5.1.3 on 2024-12-05 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0010_email_remove_blog_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=221)),
                ('image', models.ImageField(upload_to='image_student/')),
                ('description', models.TextField()),
                ('category', models.ManyToManyField(to='Article.category')),
            ],
        ),
    ]
