# Generated by Django 5.1.2 on 2024-10-22 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_book_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='file',
        ),
    ]
